In [1]:
import scanpy as sc
import anndata
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [19]:
dir = '/Users/hsieh/Tabula_muris/'
sql = 'sql_input'
droplet = 'tabula-muris-senis-droplet-processed-official-annotations.h5ad'
facs = 'tabula-muris-senis-facs-processed-official-annotations.h5ad'
fn_droplet = Path(dir, droplet)
fn_facs = Path(dir, facs)
sql_dir = Path(dir,sql)

In [20]:
method = 'droplet'
adata = sc.read_h5ad(fn_droplet)
adata

/Users/hsieh/opt/anaconda3/lib/python3.9/site-packages/anndata/compat/__init__.py:232: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  warn(
/Users/hsieh/opt/anaconda3/lib/python3.9/site-packages/anndata/compat/__init__.py:232: FutureWarning: Moving element from .uns['neighbors']['connectivities'] to .obsp['connectivities'].

This is where adjacency matrices should go now.
  warn(

AnnData object with n_obs × n_vars = 245389 × 20138
    obs: 'age', 'cell', 'cell_ontology_class', 'cell_ontology_id', 'free_annotation', 'method', 'mouse.id', 'n_genes', 'sex', 'subtissue', 'tissue', 'tissue_free_annotation', 'n_counts', 'louvain', 'leiden'
    var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'age_colors', 'leiden', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'tissue_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [4]:
# The sparse matrix
adata.X

<245389x20138 sparse matrix of type '<class 'numpy.float32'>'
	with 502072652 stored elements in Compressed Sparse Row format>

In [5]:
# Cell numbers in data set
range(adata.n_obs)

range(0, 245389)

In [6]:
# Gene numbers in data set
range(adata.n_vars)

range(0, 20138)

In [7]:
# The first 10 cells
adata.obs[:10]

,age,cell,cell_ontology_class,cell_ontology_id,free_annotation,method,mouse.id,n_genes,sex,subtissue,tissue,tissue_free_annotation,n_counts,louvain,leiden
index,,,,,,,,,,,,,,,
AAACCTGCAGGGTACA-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGCAGGGTACA,keratinocyte,NA,filiform,droplet,24-M-60,2107.0,male,nan,Tongue,Tongue,5482.0,5,8
AAACCTGCAGTAAGCG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGCAGTAAGCG,keratinocyte,NA,suprabasal,droplet,24-M-60,3481.0,male,nan,Tongue,Tongue,21855.0,19,15
AAACCTGTCATTATCC-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGTCATTATCC,keratinocyte,NA,suprabasal,droplet,24-M-60,2599.0,male,nan,Tongue,Tongue,10943.0,19,15
AAACGGGGTACAGTGG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACGGGGTACAGTGG,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3468.0,male,nan,Tongue,Tongue,20665.0,12,11
AAACGGGGTCTTCTCG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACGGGGTCTTCTCG,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3189.0,male,nan,Tongue,Tongue,12925.0,5,28
AAAGATGAGCTATGCT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGAGCTATGCT,keratinocyte,NA,suprabasal,droplet,24-M-60,3419.0,male,nan,Tongue,Tongue,20571.0,19,15
AAAGATGAGGTCGGAT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGAGGTCGGAT,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3764.0,male,nan,Tongue,Tongue,31893.0,12,11
AAAGATGGTGCAGGTA-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGGTGCAGGTA,basal cell of epidermis,NA,parabasal,droplet,24-M-60,3879.0,male,nan,Tongue,Tongue,24795.0,19,15
AAAGCAAGTAGATTAG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGCAAGTAGATTAG,keratinocyte,NA,suprabasal,droplet,24-M-60,3496.0,male,nan,Tongue,Tongue,19454.0,19,15
AAAGCAAGTATTCTCT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGCAAGTATTCTCT,keratinocyte,NA,suprabasal interpapillary,droplet,24-M-60,5439.0,male,nan,Tongue,Tongue,61449.0,12,11

In [8]:
# The first 10 genens
adata.var[:10]

         n_cells     means  dispersions  dispersions_norm  highly_variable
index
Xkr4         147  0.000552     0.630154         -0.441146            False
Rp1          233  0.000561     0.682246         -0.361406            False
Sox17      27289  0.346639     2.903749          2.040713             True
Mrpl15     95312  0.442236     0.672918         -0.618587            False
Lypla1     86096  0.409897     0.791895         -0.476758            False
Tcea1     120238  0.574355     0.729122         -0.711033            False
Rgs20       1887  0.004798     0.199002         -1.101123            False
Atp6v1h    52650  0.226831     0.680207         -0.364528            False
Oprk1         78  0.000156    -0.235658         -1.766470            False
Npbwr1       318  0.000827    -0.100931         -1.560240            False

In [23]:
# transform the raw count matrix to data frame
adata.layers["raw_data"] = adata.X
df_adata = adata.to_df(layer="raw_data")
df_adata.head(10)

index,Xkr4,Rp1,Sox17,Mrpl15,Lypla1,Tcea1,Rgs20,Atp6v1h,Oprk1,Npbwr1,...,Ddx3y,Usp9y,Rbmy1a1,LOC100039753,Rbm31y,LOC434960,LOC380994,LOC100041346,Sly,Erdr1
index,,,,,,,,,,,,,,,,,,,,,
AAACCTGCAGGGTACA-1-0-0-0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
AAACCTGCAGTAAGCG-1-0-0-0,0.0,0.0,0.0,0.000000,0.801134,0.689129,0.0,1.078693,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.730151
AAACCTGTCATTATCC-1-0-0-0,0.0,0.0,0.0,1.344208,0.000000,1.901220,0.0,0.000000,0.0,0.0,...,1.394503,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
AAACGGGGTACAGTGG-1-0-0-0,0.0,0.0,0.0,1.401824,0.000000,0.000000,0.0,1.129987,0.0,0.0,...,1.454274,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.764871
AAACGGGGTCTTCTCG-1-0-0-0,0.0,0.0,0.0,1.936402,1.218537,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.110571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10X_P8_15_TTTGTCAGTACATGTC-1,10.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
10X_P8_15_TTTGTCAGTGCGCTTG-1,0.0,0.0,0.0,0.000000,0.000000,1.797059,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.904034
10X_P8_15_TTTGTCAGTTGTCGCG-1,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,2.665223,0.0,0.0,...,1.999912,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
10X_P8_15_TTTGTCATCGGCTTGG-1,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
10X_P8_15_TTTGTCATCTTGTTTG-1,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,2.129116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.920600

In [31]:
# save count matrix to csv files
name = method+'_mtx'+'.csv'
df_adata.to_csv(Path(sql_dir,name), sep=',')

In [33]:
# Transform annotation to data frame
df_obs = pd.DataFrame(adata.obs)
df_obs.head(10)

,age,cell,cell_ontology_class,cell_ontology_id,free_annotation,method,mouse.id,n_genes,sex,subtissue,tissue,tissue_free_annotation,n_counts,louvain,leiden
index,,,,,,,,,,,,,,,
AAACCTGCAGGGTACA-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGCAGGGTACA,keratinocyte,NA,filiform,droplet,24-M-60,2107.0,male,nan,Tongue,Tongue,5482.0,5,8
AAACCTGCAGTAAGCG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGCAGTAAGCG,keratinocyte,NA,suprabasal,droplet,24-M-60,3481.0,male,nan,Tongue,Tongue,21855.0,19,15
AAACCTGTCATTATCC-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGTCATTATCC,keratinocyte,NA,suprabasal,droplet,24-M-60,2599.0,male,nan,Tongue,Tongue,10943.0,19,15
AAACGGGGTACAGTGG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACGGGGTACAGTGG,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3468.0,male,nan,Tongue,Tongue,20665.0,12,11
AAACGGGGTCTTCTCG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACGGGGTCTTCTCG,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3189.0,male,nan,Tongue,Tongue,12925.0,5,28
AAAGATGAGCTATGCT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGAGCTATGCT,keratinocyte,NA,suprabasal,droplet,24-M-60,3419.0,male,nan,Tongue,Tongue,20571.0,19,15
AAAGATGAGGTCGGAT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGAGGTCGGAT,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3764.0,male,nan,Tongue,Tongue,31893.0,12,11
AAAGATGGTGCAGGTA-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGGTGCAGGTA,basal cell of epidermis,NA,parabasal,droplet,24-M-60,3879.0,male,nan,Tongue,Tongue,24795.0,19,15
AAAGCAAGTAGATTAG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGCAAGTAGATTAG,keratinocyte,NA,suprabasal,droplet,24-M-60,3496.0,male,nan,Tongue,Tongue,19454.0,19,15
AAAGCAAGTATTCTCT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGCAAGTATTCTCT,keratinocyte,NA,suprabasal interpapillary,droplet,24-M-60,5439.0,male,nan,Tongue,Tongue,61449.0,12,11

In [35]:
name=method+'_annot'+'.csv'
df_obs.to_csv(Path(sql_dir,name), sep=',')

In [36]:
# Example codes for subsetting data 
# Check how many categories in tissue
print(df_obs['tissue'].cat.categories)

Index(['Bladder', 'Fat', 'Heart_and_Aorta', 'Kidney', 'Large_Intestine',
       'Limb_Muscle', 'Liver', 'Lung', 'Mammary_Gland', 'Marrow', 'Pancreas',
       'Skin', 'Spleen', 'Thymus', 'Tongue', 'Trachea'],
      dtype='object')

In [37]:
# Subset data from large intestine
Tissue = 'Large_Intestine'
adata_subset = adata[adata.obs['tissue'].isin([Tissue])]
adata_subset[[10],[10]]

View of AnnData object with n_obs × n_vars = 1 × 1
    obs: 'age', 'cell', 'cell_ontology_class', 'cell_ontology_id', 'free_annotation', 'method', 'mouse.id', 'n_genes', 'sex', 'subtissue', 'tissue', 'tissue_free_annotation', 'n_counts', 'louvain', 'leiden'
    var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'age_colors', 'leiden', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'tissue_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'raw_data'
    obsp: 'distances', 'connectivities'

In [38]:
## Perform natural logarithm of one plus the input array (log(x+1))
# adata_subset.layers["log_transformed"] = np.log1p(adata_subset.X)

# Output the raw counts of subsetted data
adata_subset.layers["raw_data"] = adata_subset.X
adata_subset

# transform the raw data to data frame
df_subset = adata_subset.to_df(layer="raw_data")
df_subset

index,Xkr4,Rp1,Sox17,Mrpl15,Lypla1,Tcea1,Rgs20,Atp6v1h,Oprk1,Npbwr1,...,Ddx3y,Usp9y,Rbmy1a1,LOC100039753,Rbm31y,LOC434960,LOC380994,LOC100041346,Sly,Erdr1
index,,,,,,,,,,,,,,,,,,,,,
AAACCTGGTCGAAAGC-1-8-1-0,0.0,0.0,0.0,1.901563,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.779514
AAACGGGAGTACTTGC-1-8-1-0,0.0,0.0,0.0,0.000000,1.814960,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
AAAGATGCACCAGATT-1-8-1-0,0.0,0.0,0.0,1.292620,0.000000,1.141692,0.0,1.030775,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.697716
AAATGCCGTTAAGAAC-1-8-1-0,0.0,0.0,0.0,0.000000,1.604354,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.096790
AACACGTCAGAGCCAA-1-8-1-0,0.0,0.0,0.0,0.969124,2.594070,0.855968,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTCCTCGTCCGTTAA-1-37-1-0,0.0,0.0,0.0,1.557256,0.946377,1.804357,0.0,1.274257,0.0,0.0,...,0.956168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
TTTGCGCCAGCTGGCT-1-37-1-0,0.0,0.0,0.0,0.896070,1.560170,1.764681,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
TTTGCGCGTTCCTCCA-1-37-1-0,0.0,0.0,0.0,1.510191,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
TTTGGTTGTCCGTGAC-1-37-1-0,0.0,0.0,0.0,1.882118,2.644980,0.000000,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.331285
TTTGGTTGTTTAAGCC-1-37-1-0,0.0,0.0,0.0,1.167249,0.868841,1.276425,0.0,0.644269,0.0,0.0,...,0.483442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.972037

In [40]:
# save raw count matrix to csv files
name=method+"_"+Tissue+"_mtx"+".csv"
df_subset.to_csv(Path(sql_dir,name),sep=',')

In [44]:
# Subset annotation
Tissue = ('Large_Intestine')
df_obs_subset = df_obs.loc[df_obs['tissue']==Tissue]

In [47]:
# save annotation matrix to csv files
name=method+"_"+Tissue+"_annot"+".csv"
df_obs_subset.to_csv(Path(sql_dir,name),sep=',')