In [6]:
import scanpy as sc
import anndata
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [7]:
dir = '/Users/hsieh/Library/CloudStorage/Box-Box/Per_170768_Tsung-Han Hsieh/RNAseq/Tabula_muris/'
droplet = 'tabula-muris-senis-droplet-processed-official-annotations.h5ad'
facs = 'tabula-muris-senis-facs-processed-official-annotations.h5ad'
fn_droplet = Path(dir, droplet)
print(fn_droplet)

/Users/hsieh/Library/CloudStorage/Box-Box/Per_170768_Tsung-Han Hsieh/RNAseq/Tabula_muris/tabula-muris-senis-droplet-processed-official-annotations.h5ad

In [8]:
adata = sc.read_h5ad(fn_droplet)
adata

/Users/hsieh/opt/anaconda3/lib/python3.9/site-packages/anndata/compat/__init__.py:232: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  warn(
/Users/hsieh/opt/anaconda3/lib/python3.9/site-packages/anndata/compat/__init__.py:232: FutureWarning: Moving element from .uns['neighbors']['connectivities'] to .obsp['connectivities'].

This is where adjacency matrices should go now.
  warn(

AnnData object with n_obs × n_vars = 245389 × 20138
    obs: 'age', 'cell', 'cell_ontology_class', 'cell_ontology_id', 'free_annotation', 'method', 'mouse.id', 'n_genes', 'sex', 'subtissue', 'tissue', 'tissue_free_annotation', 'n_counts', 'louvain', 'leiden'
    var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'age_colors', 'leiden', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'tissue_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [9]:
# The sparse matrix
adata.X

<245389x20138 sparse matrix of type '<class 'numpy.float32'>'
	with 502072652 stored elements in Compressed Sparse Row format>

In [10]:
# Cell numbers in data set
range(adata.n_obs)

range(0, 245389)

In [11]:
# Gene numbers in data set
range(adata.n_vars)

range(0, 20138)

In [12]:
# The first 10 cells
adata.obs[:10]

,age,cell,cell_ontology_class,cell_ontology_id,free_annotation,method,mouse.id,n_genes,sex,subtissue,tissue,tissue_free_annotation,n_counts,louvain,leiden
index,,,,,,,,,,,,,,,
AAACCTGCAGGGTACA-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGCAGGGTACA,keratinocyte,NA,filiform,droplet,24-M-60,2107.0,male,nan,Tongue,Tongue,5482.0,5,8
AAACCTGCAGTAAGCG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGCAGTAAGCG,keratinocyte,NA,suprabasal,droplet,24-M-60,3481.0,male,nan,Tongue,Tongue,21855.0,19,15
AAACCTGTCATTATCC-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACCTGTCATTATCC,keratinocyte,NA,suprabasal,droplet,24-M-60,2599.0,male,nan,Tongue,Tongue,10943.0,19,15
AAACGGGGTACAGTGG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACGGGGTACAGTGG,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3468.0,male,nan,Tongue,Tongue,20665.0,12,11
AAACGGGGTCTTCTCG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAACGGGGTCTTCTCG,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3189.0,male,nan,Tongue,Tongue,12925.0,5,28
AAAGATGAGCTATGCT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGAGCTATGCT,keratinocyte,NA,suprabasal,droplet,24-M-60,3419.0,male,nan,Tongue,Tongue,20571.0,19,15
AAAGATGAGGTCGGAT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGAGGTCGGAT,keratinocyte,NA,suprabasal differentiating,droplet,24-M-60,3764.0,male,nan,Tongue,Tongue,31893.0,12,11
AAAGATGGTGCAGGTA-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGATGGTGCAGGTA,basal cell of epidermis,NA,parabasal,droplet,24-M-60,3879.0,male,nan,Tongue,Tongue,24795.0,19,15
AAAGCAAGTAGATTAG-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGCAAGTAGATTAG,keratinocyte,NA,suprabasal,droplet,24-M-60,3496.0,male,nan,Tongue,Tongue,19454.0,19,15
AAAGCAAGTATTCTCT-1-0-0-0,24m,MACA_24m_M_TONGUE_60_AAAGCAAGTATTCTCT,keratinocyte,NA,suprabasal interpapillary,droplet,24-M-60,5439.0,male,nan,Tongue,Tongue,61449.0,12,11

In [13]:
# The first 10 genens
adata.var[:10]

         n_cells     means  dispersions  dispersions_norm  highly_variable
index
Xkr4         147  0.000552     0.630154         -0.441146            False
Rp1          233  0.000561     0.682246         -0.361406            False
Sox17      27289  0.346639     2.903749          2.040713             True
Mrpl15     95312  0.442236     0.672918         -0.618587            False
Lypla1     86096  0.409897     0.791895         -0.476758            False
Tcea1     120238  0.574355     0.729122         -0.711033            False
Rgs20       1887  0.004798     0.199002         -1.101123            False
Atp6v1h    52650  0.226831     0.680207         -0.364528            False
Oprk1         78  0.000156    -0.235658         -1.766470            False
Npbwr1       318  0.000827    -0.100931         -1.560240            False

In [17]:
# Example codes for subsetting data, the first two cells x the first two genes
adata[[0,1],[0,1]]

View of AnnData object with n_obs × n_vars = 2 × 2
    obs: 'age', 'cell', 'cell_ontology_class', 'cell_ontology_id', 'free_annotation', 'method', 'mouse.id', 'n_genes', 'sex', 'subtissue', 'tissue', 'tissue_free_annotation', 'n_counts', 'louvain', 'leiden'
    var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'age_colors', 'leiden', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'tissue_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [18]:
# Subsetting data
# I want to know how many categories in each column, so I transform the obs to data frame
# and use the pandas function to have this information
# transform the original objects to padas dataframe
df_obs = pd.DataFrame(adata.obs)

# Take a look at the obs data frame
# print(df_obs.head(n=10))
      
# Check how many categories in tissue
print(df_obs['tissue'].cat.categories)

Index(['Bladder', 'Fat', 'Heart_and_Aorta', 'Kidney', 'Large_Intestine',
       'Limb_Muscle', 'Liver', 'Lung', 'Mammary_Gland', 'Marrow', 'Pancreas',
       'Skin', 'Spleen', 'Thymus', 'Tongue', 'Trachea'],
      dtype='object')

In [29]:
# Subset data, only data from intestine are needes
adata_subset = adata[adata.obs['tissue'].isin(['Small-Intestine','Large-Intestine'])]
adata_subset

View of AnnData object with n_obs × n_vars = 29882 × 17446
    obs: 'nCount_RNA', 'nFeature_RNA', 'sampleID', 'tissue', 'model', 'age', 'model_age', 'mouseID', 'doublet_scores', 'percent.mt', 'percent.ribo', 'percent.hb', 'percent.hist', 'S.Score', 'G2M.Score', 'group_umap_sub', 'annotation_lv0', 'annotation_lv1', 'annotation_lv2', 'annotation_lv3', 'phase'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    obsm: 'X_tsne', 'X_umap', 'X_umap_sub', 'X_umap_tissue'

In [30]:
# Perform log transform to the subsetted data
# adata_subset.layers["log_transformed"] = np.log1p(adata_subset.X)
# adata_subset

# Cibersortx does not require data to be log-transformed
adata_subset.layers["raw_data"] = adata_subset.X
adata_subset

AnnData object with n_obs × n_vars = 29882 × 17446
    obs: 'nCount_RNA', 'nFeature_RNA', 'sampleID', 'tissue', 'model', 'age', 'model_age', 'mouseID', 'doublet_scores', 'percent.mt', 'percent.ribo', 'percent.hb', 'percent.hist', 'S.Score', 'G2M.Score', 'group_umap_sub', 'annotation_lv0', 'annotation_lv1', 'annotation_lv2', 'annotation_lv3', 'phase'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    obsm: 'X_tsne', 'X_umap', 'X_umap_sub', 'X_umap_tissue'
    layers: 'raw_data'

In [32]:
# transform the raw data to data frame
df_subset = adata_subset.to_df(layer="raw_data")
df_subset

,Xkr4,Gm19938,Sox17,Mrpl15,Lypla1,Tcea1,Rgs20,Atp6v1h,Npbwr1,Rb1cc1,...,AC168977.1,CAAA01118383.1,AC132444.1,Csprs,Vamp7,Spry3,Tmlhe,CR974586.4,CAAA01147332.1,AC149090.1
111524,0.0,0.0,0.000000,2.207373,2.424684,0.551364,0.0,0.551364,0.0,0.551364,...,0.0,0.000000,0.0,0.0,0.904719,0.904719,0.551364,0.0,0.0,0.904719
111525,0.0,0.0,0.000000,1.260857,2.481283,0.611294,0.0,0.611294,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.611294,0.0,0.0,0.987915
111526,0.0,0.0,0.000000,0.000000,1.331934,1.050440,0.0,0.657237,0.0,1.050440,...,0.0,0.000000,0.0,0.0,1.331934,0.000000,0.657237,0.0,0.0,0.000000
111527,0.0,0.0,0.000000,1.100081,1.387947,0.694249,0.0,0.000000,0.0,0.694249,...,0.0,0.694249,0.0,0.0,0.694249,0.000000,1.100081,0.0,0.0,0.694249
111528,0.0,0.0,0.000000,1.812044,1.628919,0.705367,0.0,0.000000,0.0,0.705367,...,0.0,0.705367,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,1.812044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181813,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
181814,0.0,0.0,0.000000,2.375473,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
181815,0.0,0.0,2.384369,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
181816,0.0,0.0,0.000000,0.000000,0.000000,2.385264,0.0,0.000000,0.0,2.385264,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
181817,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000

In [33]:
# I only need cell type from annotation_lv2
# So let's just keep this column for the subsequent process
df_obs_subset = df_obs['annotation_lv2']
df_subset_new = pd.merge(df_subset, df_obs_subset, left_index=True, right_index=True)
df_subset_new

,Xkr4,Gm19938,Sox17,Mrpl15,Lypla1,Tcea1,Rgs20,Atp6v1h,Npbwr1,Rb1cc1,...,CAAA01118383.1,AC132444.1,Csprs,Vamp7,Spry3,Tmlhe,CR974586.4,CAAA01147332.1,AC149090.1,annotation_lv2
111524,0.0,0.0,0.000000,2.207373,2.424684,0.551364,0.0,0.551364,0.0,0.551364,...,0.000000,0.0,0.0,0.904719,0.904719,0.551364,0.0,0.0,0.904719,enterocyte
111525,0.0,0.0,0.000000,1.260857,2.481283,0.611294,0.0,0.611294,0.0,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.611294,0.0,0.0,0.987915,enterocyte
111526,0.0,0.0,0.000000,0.000000,1.331934,1.050440,0.0,0.657237,0.0,1.050440,...,0.000000,0.0,0.0,1.331934,0.000000,0.657237,0.0,0.0,0.000000,enterocyte
111527,0.0,0.0,0.000000,1.100081,1.387947,0.694249,0.0,0.000000,0.0,0.694249,...,0.694249,0.0,0.0,0.694249,0.000000,1.100081,0.0,0.0,0.694249,enterocyte
111528,0.0,0.0,0.000000,1.812044,1.628919,0.705367,0.0,0.000000,0.0,0.705367,...,0.705367,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,1.812044,enterocyte
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181813,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,endothelial cell
181814,0.0,0.0,0.000000,2.375473,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,intestinal stem cell
181815,0.0,0.0,2.384369,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,endothelial cell
181816,0.0,0.0,0.000000,0.000000,0.000000,2.385264,0.0,0.000000,0.0,2.385264,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,goblet cell
181817,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,low-quality cell

In [38]:
df_subset_new_transposed = df_subset_new.T
df_subset_new_transposed

,111524,111525,111526,111527,111528,111529,111530,111531,111532,111533,...,181808,181809,181810,181811,181812,181813,181814,181815,181816,181817
Xkr4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gm19938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sox17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.352779,0.0,0.0,0.0,0.0,0.0,2.384369,0.0,0.0
Mrpl15,2.207373,1.260857,0.0,1.100081,1.812044,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.375473,0.0,0.0,0.0
Lypla1,2.424684,2.481283,1.331934,1.387947,1.628919,0.7174,1.151256,0.760074,1.217906,0.844337,...,0.0,0.0,0.0,2.3502,2.341661,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tmlhe,0.551364,0.611294,0.657237,1.100081,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CR974586.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CAAA01147332.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AC149090.1,0.904719,0.987915,0.0,0.694249,1.812044,0.0,0.0,0.0,1.217906,1.295514,...,0.0,0.0,2.364921,0.0,0.0,0.0,0.0,0.0,0.0,0.0
annotation_lv2,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enteroendocrine cell,enterocyte,...,macrophage,endothelial cell,memory CD8 T cell,intestinal stem cell,intestinal stem cell,endothelial cell,intestinal stem cell,endothelial cell,goblet cell,low-quality cell

In [41]:
# Separate the count matrix and cell annotation matrix
# Get the count matrix first and save it
sc_matrix = df_subset_new_transposed.drop(index='annotation_lv2')
sc_matrix.to_csv(dir+"scRNA_count.txt", sep="\t")
sc_matrix

,111524,111525,111526,111527,111528,111529,111530,111531,111532,111533,...,181808,181809,181810,181811,181812,181813,181814,181815,181816,181817
Xkr4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gm19938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sox17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.352779,0.0,0.0,0.0,0.0,0.0,2.384369,0.0,0.0
Mrpl15,2.207373,1.260857,0.0,1.100081,1.812044,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.375473,0.0,0.0,0.0
Lypla1,2.424684,2.481283,1.331934,1.387947,1.628919,0.7174,1.151256,0.760074,1.217906,0.844337,...,0.0,0.0,0.0,2.3502,2.341661,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spry3,0.904719,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tmlhe,0.551364,0.611294,0.657237,1.100081,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CR974586.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CAAA01147332.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AC149090.1,0.904719,0.987915,0.0,0.694249,1.812044,0.0,0.0,0.0,1.217906,1.295514,...,0.0,0.0,2.364921,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
sc_matrix.to_csv(dir+"scRNA_count.txt", sep="\t")

In [50]:
# Get the annotation matrix and save it
annotation = df_subset_new_transposed.loc["annotation_lv2"].to_frame()
annotation.to_csv(dir+"cell_annotation.txt", sep="\t")
annotation

              annotation_lv2
111524            enterocyte
111525            enterocyte
111526            enterocyte
111527            enterocyte
111528            enterocyte
...                      ...
181813      endothelial cell
181814  intestinal stem cell
181815      endothelial cell
181816           goblet cell
181817      low-quality cell

[29882 rows x 1 columns]

In [35]:
# This step is specifically for CIBERSORTx website
# Rename the column
df_cibersortx = df_subset_new_transposed
df_cibersortx.columns = df_cibersortx.iloc[df_cibersortx.shape[0]-1]
df_cibersortx = df_cibersortx.drop(index='annotation_lv2')
df_cibersortxd = df_cibersortx.rename(columns={'annotation_lv2': 'GeneSymbol'})
df_cibersortx
# Write data into txt file
df_cibersortx.to_csv(dir+"CIBERSORTx_intestine_cell_index.txt", sep="\t")

annotation_lv2,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enterocyte,enteroendocrine cell,enterocyte,...,macrophage,endothelial cell,memory CD8 T cell,intestinal stem cell,intestinal stem cell,endothelial cell,intestinal stem cell,endothelial cell,goblet cell,low-quality cell
Xkr4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gm19938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sox17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.352779,0.0,0.0,0.0,0.0,0.0,2.384369,0.0,0.0
Mrpl15,2.207373,1.260857,0.0,1.100081,1.812044,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.375473,0.0,0.0,0.0
Lypla1,2.424684,2.481283,1.331934,1.387947,1.628919,0.7174,1.151256,0.760074,1.217906,0.844337,...,0.0,0.0,0.0,2.3502,2.341661,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spry3,0.904719,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tmlhe,0.551364,0.611294,0.657237,1.100081,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CR974586.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CAAA01147332.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AC149090.1,0.904719,0.987915,0.0,0.694249,1.812044,0.0,0.0,0.0,1.217906,1.295514,...,0.0,0.0,2.364921,0.0,0.0,0.0,0.0,0.0,0.0,0.0